# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170404_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='message',
            name='uuid',
        ),
        migrations.AddField(
            model_name='chat',
            name='uuid_id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='message',
            name='uuid_id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
