# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kryptuser',
            name='email',
        ),
        migrations.AddField(
            model_name='kryptuser',
            name='username',
            field=models.CharField(default='user', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
