# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170501_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kryptuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
