# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 01:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_kryptuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kryptuser',
            name='contacts',
            field=models.ManyToManyField(blank=True, null=True, related_name='added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kryptuser',
            name='contacts_request',
            field=models.ManyToManyField(blank=True, null=True, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
