# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170504_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='uuid_id',
        ),
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
