# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 01:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170504_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_to',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='my_messages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
